#!/bin/bash
function dx11 {
	cgc -q -profile vs_5_0 -entry vs -o compiled/${f%.*}.shader.dx11.vertex $f
	cgc -q -profile ps_5_0 -entry ps -o compiled/${f%.*}.shader.dx11.fragment $f
}
function gl21 {
	cgc -q -profile glslv -entry vs -o compiled/${f%.*}.shader.gl21.vertex $f
	cgc -q -profile glslf -entry ps -o compiled/${f%.*}.shader.gl21.fragment $f
}
function gcm {
	sce-cgc -q -p sce_vp_rsx -e vs -o compiled/${f%.*}.shader.gcm.vertex $f
	sce-cgc -q -p sce_fp_rsx -e ps -o compiled/${f%.*}.shader.gcm.fragment $f
}
function shader {
	dx11
	gl21
	gcm
}
for f in *.cg ; do
	shader
done