#!/bin/bash
function dx11 {
	cgc -DDX11=1 -q -unroll all -profile vs_5_0 -entry vs -o compiled/${f%.*}.shader.dx11.vertex $f
	cgc -DDX11=1 -q -unroll all -profile ps_5_0 -entry ps -o compiled/${f%.*}.shader.dx11.fragment $f
}
function gl21 {
	cgc -DGL21=1 -q -profile glslv -entry vs -o compiled/${f%.*}.shader.gl21.vertex $f
	cgc -DGL21=1 -q -profile glslf -entry ps -o compiled/${f%.*}.shader.gl21.fragment $f
}
function gcm {
	sce-cgc --capture --capture-dir compiled --debug --fenable-bx2 --fastmath --fastprecision --nofloatbindings -DGCM=1 -q -p sce_vp_rsx -e vs -o compiled/${f%.*}.shader.gcm.vertex $f
	sce-cgc --capture --capture-dir compiled --debug --fenable-bx2 --fastmath --fastprecision --nofloatbindings -DGCM=1 -q -p sce_fp_rsx -e ps -o compiled/${f%.*}.shader.gcm.fragment $f
}
function shader {
	dx11
	gl21
	gcm
}
if [ "$1" = "-a" ] ; then
	echo "Compiling all shaders:"
	for f in *.cg ; do
		echo
		echo $f
		shader
	done
	echo
	echo "done!"
fi
if [ "$1" = "-s" ] ; then
	echo
	fullfile=$2
	pathfile=${fullfile//[\\:CD]//}
	file=${pathfile/\/*\//}
	echo "Compiling single shader: $file"
	f="$file"
	echo
	shader
	echo
fi