#include "standard.h"

uniform sampler2D ColorMap : TEXUNIT0;

uniform float2 HalfPixel;

struct VOutput {
	float4 position			: POSITION;
	float2 texCoord			: TEXCOORD0;
};

VOutput vs(float4 position 			: POSITION,
		   		 float2 texCoord : TEXCOORD0) {
	VOutput OUT;
	OUT.position = position;
	OUT.texCoord = texCoord;
 	return OUT;
}

float4 ps(float4 position : POSITION,
		  float2 texCoord : TEXCOORD0) : COLOR0 {
	return tex2D(ColorMap, texCoord + HalfPixel);
} 