uniform sampler2D DepthMap : TEXUNIT0;

struct VOutput {
	float4 position			: POSITION;
	float2 texCoord			: TEXCOORD0;
};

VOutput vs(float4 position 			: POSITION,
		   float2 texCoord 			: TEXCOORD0) {
	VOutput OUT;
	OUT.position = position;
	OUT.texCoord = texCoord;
 	return OUT;
}

float4 ps(float4 position : POSITION,
		  float2 texCoord : TEXCOORD0) : COLOR0 {
	float depth = tex2D(DepthMap, texCoord).r;
	return float4(1, 1, 0, 1);
} 