uniform float4x4 ModelProjection;

sampler2D ColorMap;

struct VOutput {
	float4 position		: POSITION;
	float2 texCoord 	: TEXCOORD0;
};

VOutput vs(float4 position : POSITION,
		 	     float2 texCoord : TEXCOORD0) {
	VOutput OUT;
	OUT.position = mul(ModelProjection, position);
	OUT.texCoord = texCoord;
 	return OUT;
}

float4 ps(float4 position		: POSITION,
		      float2 texCoord 	: TEXCOORD0) : COLOR0 {
	return tex2D(ColorMap, texCoord);
}