sampler2D ColorMap;
sampler2D LightSourceMap;

float4 ps(float4 position : POSITION,
          float2 texCoord : TEXCOORD0) : COLOR0 {
  float4 diffuseColor = tex2D(ColorMap, texCoord);
  float4 diffuseLight = tex2D(LightSourceMap, texCoord);
  float3 finalColor = diffuseColor.rgb * diffuseLight.rgb + diffuseLight.w;
  return float4(diffuseLight.rgb, diffuseColor.a);
}

// need to additive blend here