float4 main(float4 vPosition  : TEXCOORD0, 
            float3 normal     : TEXCOORD1,
            uniform float4 ambient,
			      uniform float4 diffuse,
            uniform float4 lightPosition) : COLOR {


  float4 lightDirection = lightPosition - vPosition;
  float diffuseStrength = max(0.0f, dot(normalize(normal), normalize(lightDirection)));

  float4 diffuseAmount = diffuse * diffuseStrength;
  float4 finalColor = diffuseAmount + ambient;

  return finalColor;
}